[package]
name = "callbacks"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
thiserror = "1"
tokio = { version = "1.40", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.4"
serde_json = "1.0"
hex = "0.4"

[build-dependencies]
cc = "1.0"
